### ISSUE TITLE
Verlinkung Quellenangabe zu Literaturverzeichnis möglich?

### ISSUE THREAD

**Issue by HansRoulade** [Perlo0ung/htwg_thesis_template_markdown#4]
Vielen Dank für dieses Template. Habe es für eine Masterarbeit etwas abgeändert.

Die Verlinkung von Fußnoten im Text bewirkt ja on-click einen Sprung in die Fußzeile zum entsprechenden Eintrag; dieser Link wird im YAML-File mit linkcolor eingefärbt. Ist dasselbe Verhalten auch für die Quellenangaben mit Sprung zum entsprechenden Eintrag im Literaturverzeichnis möglich - und wenn ja, wie...?

**Comment by Perlo0ung** [comment]
Du könntest mal das versuchen:
https://golatex.de/viewtopic.php?t=3286

**Comment by HansRoulade** [comment]
Das hat leider nicht den erhofften Erfolg gebracht.

Ich bin dann aber an anderer Stelle auf die Lösung gestoßen:
Im YAML-File muss lediglich
`link-citations: true`
eingefügt werden - schon funktioniert's.

Besten Dank trotzdem!

**Comment by Perlo0ung** [comment]
Top, danke für die Rückmeldung, hilft evtl mal jemand in der Zukunft :) Hab es im settings.yaml erwähnt

**Comment by HansRoulade** [comment]
Super!

Noch eine kleine Anpassung, die ich für nötig hielt:
`lot: true`

Die Reihenfolge von Abbildungs- und Tabellenverzeichnis lässt sich in der ba_template.tex ändern:
`$if(lof)$`
`\listoffigures`
`$endif$`
`$if(lot)$`
`\listoftables`
`$endif$`

Jetzt muss ich nur noch dahinter kommen, wie es mit dem Abkürzungsverzeichnis aussieht...
