### ISSUE TITLE
! LaTeX Error: Environment cslreferences undefined. [solved]

### ISSUE THREAD

**Issue by spiraleye86** [Perlo0ung/htwg_thesis_template_markdown#5]
Hi,
vielen Dank für die Vorlage!!!

Beim Erstellen der pdf mit pandoc bekomme ich den Fehler 

! LaTeX Error: Environment cslreferences undefined.

Durch Einfügen des unten stehenden Codes am Anfang von ba_template.tex konnte dies behoben werden. 
Siehe dazu auch: https://github.com/rstudio/rmarkdown/issues/1649

% in order to get rid of error: "! LaTeX Error: Environment cslreferences undefined."
$if(csl-refs)$
\newlength{\cslhangindent}
\setlength{\cslhangindent}{1.5em}
\newenvironment{cslreferences}%
{$if(csl-hanging-indent)$\setlength{\parindent}{0pt}%
\everypar{\setlength{\hangindent}{\cslhangindent}}\ignorespaces$endif$}%
{\par}
$endif$

Meine ba_template.tex sieht also nun in den ersten Zeilen folgendermaßen aus:

\documentclass[$if(fontsize)$$fontsize$,$endif$$if(lang)$$babel-lang$,$endif$$if(papersize)$$papersize$,$endif$$for(classoption)$$classoption$$sep$,$endfor$]{$documentclass$}
%Imports
\usepackage[]{titlesec}
\usepackage{graphicx}
\usepackage{fancyhdr}
\usepackage{color}
\usepackage{biblatex}
\usepackage{listings}
\usepackage{caption}
\usepackage{chngcntr}
\usepackage{csquotes}

% in order to get rid of error: "! LaTeX Error: Environment cslreferences undefined."
$if(csl-refs)$
\newlength{\cslhangindent}
\setlength{\cslhangindent}{1.5em}
\newenvironment{cslreferences}%
{$if(csl-hanging-indent)$\setlength{\parindent}{0pt}%
\everypar{\setlength{\hangindent}{\cslhangindent}}\ignorespaces$endif$}%
{\par}
$endif$

%markdown codeblock size
\makeatletter
\def\verbatim{\footnotesize\@verbatim \frenchspacing\@vobeyspaces \@xverbatim}
\makeatother

%document settings
\MakeOuterQuote{"}
\counterwithout{footnote}{chapter} %dont reset footnotes in new chapter

**Comment by Perlo0ung** [comment]
Danke für die Info, kannst du dafür einen Pull request erstellen?

**Comment by spiraleye86** [comment]
Ja, könnte ich machen, allerdings weiß ich nicht, wie das geht. Aber kann mal schauen, ob ich das herausfinde. :D  Bisher habe ich GitHub noch nicht so viel benutzt.


Am Wed, 08 Jul 2020 12:14:45 -0700, Michael Offergeld <notifications@github.com> schrieb:
 
 

Danke für die Info, kannst du dafür einen Pull request erstellen?

**Comment by Perlo0ung** [comment]
siehe #6
